### ISSUE TITLE
왼쪽내브바 작동

### ISSUE THREAD

**Issue by SeaJungg** [FromNode/FromNode_Project#54]

**Comment by HyeseonLee** [comment]
프로젝트 연결은 완료

**Comment by HyeseonLee** [comment]
`{% block leftbar %}
    <div class="side-box">
        <p class="side-title">내 프로젝트</p>
        {% for project in proj_obj %}
        <ul class="side-content">
            <li class="side-project-name"><a  href="{% url 'file:file_list' project.id %}" style="color: black"><p>프로젝트{{project.id}} : {{project.name}}</p></a></li>
        </ul>
        {% endfor %}
    </div>

    <div class="side-box">
        <p class="side-title ">최종 파일 모음</p>
    </div>
{% endblock %}
`
